version: "3.8"
services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "${BACKEND_PORT}:${BACKEND_PORT}"
  #   environment:
  #     - PORT=${BACKEND_PORT}
  #   volumes:
  #     - ./backend/src:/app/src

  database:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    
volumes:
  postgres:
