# version: "3.8"
# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile.dev
#     ports:
#       - "5000:5000"
#     depends_on:
#       database:
#         condition: service_healthy
#     environment:
#       PORT: 5000
#       DATABASE_URL: "postgresql://postgres:postgres@db:5432/mydb?schema=public"
#     volumes:
#       - ./backend/src:/app/src

#   database:
#     image: postgres:13
#     volumes:
#       - postgres:/var/lib/postgresql/data
#     restart: always
#     environment:
#       - POSTGRES_USER: 'postgres'
#       - POSTGRES_PASSWORD: 'postgres'
#       - POSTGRES_DB: 'mydb'
#     ports:
#       - "2345:5432"
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
    
# volumes:
#   postgres:

version: "3.9"

services:
  database:
    image: "postgres"
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "mydb"
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/mydb?schema=public"
      PORT: "4000"
    env_file: .env.dev
    volumes:
      - ./backend/src:/app/src