version: "3.8"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_c
    networks:
      - webnet
    volumes:
      - ./backend:/app

  database:
    image:  mysql:5.7
    container_name: database_c
    networks:
      - webnet
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
 
networks:
  webnet:

volumes:
  mysql: