version: "3.9"

services:
  database:
    image: "postgres"
    ports:
      - "2345:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: "${BACKEND_PORT}"
    env_file: .env.dev
    volumes:
      - ./backend/prisma:/app/prisma:ro
      - ./backend/src:/app/src:ro
      - ./backend/tests:/app/tests:ro
    depends_on:
      database:
        condition: service_healthy
