version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - PORT=${BACKEND_PORT}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend/src:/app/src

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"
  #   environment:
  #     - PORT=${FRONTEND_PORT}
  
  database:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    
volumes:
  postgres:
