version: "3.9"

services:
  database:
    image: "postgres"
    ports:
      - "2345:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: "${BACKEND_PORT}"
    env_file: .env.dev
    volumes:
      - ./backend/src:/app/src