FROM node:18-alpine
WORKDIR /app

COPY package.json .
COPY tsconfig.json .
COPY yarn.lock .
RUN yarn install

COPY ./prisma ./prisma
RUN npx prisma generate
RUN npx prisma migrate

CMD ["yarn", "dev"]