FROM node:18-alpine
WORKDIR /app

COPY package.json .
COPY yarn.lock .
RUN yarn install
COPY tsconfig.json .

COPY ./prisma ./prisma
RUN npx prisma generate

COPY .env .
RUN npx prisma migrate dev --name init

CMD ["yarn", "dev"]