name: Node.js CI

on:
  push:
    branches: [ main ]
    paths: ['backend/**']
  pull_request:
    branches: [ main ]
    paths: ['backend/**']

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:  
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: yarn lint
      - name: Check formatting

      - run: yarn test
      - name: Run Jest tests