name: "Backend testing"

on:
  pull_request:
    branches: [main]
    paths: ['backend/**']
  push:
    branches: [main]
    paths: ['backend/**']

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run integration tests"
        run: yarn test:start