name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:  
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean install
        run: yarn config set ignore-engines true && yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - run: yarn test
        name: Run Jest tests