# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - docker build -t $REPO_URL $FOLDER_PATH
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPO_URL:$IMAGE_TAG

      - echo Changing directory to templates directory
      - cd ./infra/templates
      - echo Preparing spec files in new folder
      - mkdir artifacts

artifacts:
  files:
    - '**/*'
  base-directory: 'infra/templates'
  discard-paths: yes